# ------------------------------------------------------------------------------ #
#                             Create header lib                                  #
# ------------------------------------------------------------------------------ #

message("Adding the COMET library...")

add_library(${LIB_NAME} INTERFACE)

# ------------------------------------------------------------------------------ #
#                               Load files                                       #
# ------------------------------------------------------------------------------ #

target_include_directories(${LIB_NAME} INTERFACE ..)